name: canary-publish

on:
  push:
    branches:
      - 'feature/**'

env:
  NODE_VERSION: '16.x'
  NPM_REGISTRY_URL: 'https://npm.pkg.github.com/'

jobs:
  canary:
    if: "!contains(github.event.head_commit.message, 'skip canary')"

    runs-on: ubuntu-latest

    steps:
      - name: 🧰 set node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - uses: actions/checkout@v3

      - name: 🗂 depenency install
        run: npm ci

      - name: 🦜 canary deploy
        run: npm run deploy:canary
