name: CI

on:
  push:
    branches:
      - 'feature/**'
      - 'release/**'

env:
  NODE_VERSION: '16.x'
  NPM_REGISTRY_URL: 'https://npm.pkg.github.com/'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: 🧰 use node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - uses: actions/checkout@v3

      - name: 🗂 depenency install
        run: npm install

      - name: ✅ check lint
        run: npm run lint

      - name: ✅ check prettier
        run: npm run prettier
